repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
      - id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
-   repo: local
    hooks:
      - id: flakeheaven
        name: flakeheaven
        description: "flakeheaven wraps flake8. (flakehell is deprecated)"
        entry: flakeheaven
        args: [lint]
        language: python
        types: [python]
        require_serial: true
        additional_dependencies: [
          'flake8>=4.0.1,<5.0.0',
          'flakeheaven~=3.2.1',
          'flake8-builtins~=2.0.1',
          'flake8-blind-except~=0.2.1',
          'flake8-logging-format~=0.9.0',
          'flake8-bugbear~=22.10.27',
          'flake8-annotations~=2.9.1',
          'flake8-docstrings~=1.6.0',
          'flake8-bandit==3.0.0',
          'darglint~=1.8.1'
        ]
